= How to set up Hawkular + Cassandra Cluster

== Requirements.

For this tutorial I'm going to assume that you have RedHat Atomic Host 7.2 and docker installed on your system. In this tutorial we are going to see how we can setup our Cassandra cluster shrink or expand our Cassandra cluster.

== How to expand the cluster

If for some reason we need to expand our cluster to have more than one node, if this is gonna be on the same box we can launch a new container with this command:

[source, bash]
----
docker run -d -e CASSANDRA_START_RPC=true pilhuhn/hawkular-services:latest
----

After launching the container, you can check the status of the node with nodetool,

Once the node is up, you need to execute a cleanup process on the other nodes of the cluster, you can do this operation latter
Repeat this process for each node you want to add to the cluster.

== How to shrink the cluster

If for some reason you need to remove a node form the cluster, you need to follow the following steps:

. Select a node you want to remove form the cluster, you can see all containers running with `docker ps`
. Once you selected a node check whether the node is up or down using `nodetool status`
. You need to run a decommission process, this will assign the ranges the old node was responsible for to other nodes, and replicate the appropriate data.{blank}
[source, bash]
----
  docker exec -it <container_id> /usr/bin/nodetool decommission
----
You can monitor the progress using `docker exec -it <container_id> /usr/bin/nodetool netstats`
.

Once the process finish you can safely delete the container

[source, bash]
----
  docker stop <container_id>
  docker rm <container_id>
----
