= Setup Cassandra cluster


== Adding Nodes

If for some reason the cluster needs to be expanded on the same box, this can be accomplished launching new Cassandra container and make it point to the seed container.
Make sure to provide a valid seed container so the new node can bootstrap properly.

[source, bash]
----
docker run -d -e CASSANDRA_SEEDS=cassandra_seed -d \
              -e CASSANDRA_START_RPC=true  \
              --link cassandra_seed  \
              brew-pulp-docker01.web.prod.ext.phx2.redhat.com:8888/jboss/cassandra:latest
----

Verify the container is launched using `docker ps`, then verify the status of the node, this can be done running the `nodetool` command
inside the container.

----
#  docker exec -it <container_id /opt/apache-cassandra/bin/nodetool status

Datacenter: datacenter1
=======================
Status=Up/Down
|/ State=Normal/Leaving/Joining/Moving
--  Address     Load       Tokens       Owns (effective)  Host ID                               Rack
UN  172.17.0.2  490.35 KB  256          50.2%             ead3a0ee-b040-4873-8b62-aa700d02b0c1  rack1
UN  172.17.0.4  312.28 KB  256          49.8%             8e4a73eb-5545-48e1-9464-ef2728f8852e  rack1
----

Once all nodes appear UP the cleanup process needs to run in each other nodes of the cluster. This operation removes all unnecessary keys
that don't belong to the node itself. The cleanup operation can be done using nodetool inside each container.

---
docker exec -it <container_id> /opt/apache-cassandra/bin/nodetool cleanup
---

The cleanup process needs temporary disk space (proportional to the amount of data stored) and is an I/O intensive operation, so it can be postponed to lower usage hours.

This process could be repeated each time wants to add a node to the cluster.

== Remove a node.

For remove a node from the cluster those are the steps:

. Select a node for be removed form the cluster, the list of nodes can be obtained running `docker ps`
. Once the node is selected check whether the node is up or down using `nodetool status`
. Then a decommission process needs to run inside the container,
 this process will assign the ranges the old node was responsible for to other nodes, and replicate the appropriate data.{blank}

[source, bash]
----
  docker exec -it <container_id> /usr/bin/nodetool decommission
----
The progress of the process can be monitored using the command: `docker exec -it <container_id> /usr/bin/nodetool netstats`
.

----
docker exec -it <container_id> /opt/apache-cassandra/bin/nodetool netstats

Mode: DECOMMISSIONED
Not sending any streams.
Read Repair Statistics:
----

. Once the process finish the container can be safely deleted.

[source, bash]
----
docker stop <container_id>
docker rm <container_id>
----

or

----
docker rm --force  <container_id>
----
