= Prerequisite

To manage Red Hat Middleware servers with CloudForms, the following pieces are
required to be properly installed

. Red Hat CloudForms
. Red Hat Entrerprise Linux with Docker
. A PostgreSQL Server

== Installing Red Hat CloudForms Server 4.2
To install Red Hat CloudForms Server, please refer to
link:https://access.redhat.com/documentation/en/red-hat-cloudforms/[its installation guide]

== Installing Red Hat Enterprise Linux 7.2 or higher
To run the Middleware Manager, a successful installation of RHEL 7.2 or higher is
required. The machine needs to be registered.
Please refer to the
link:https://access.redhat.com/documentation/en/red-hat-enterprise-linux/[Red Hat Enterprise Linux installation guide.]

To register and add extra repositories for Docker support:
[source, bash]
----
subscription-manager register --username=<rhnuser> --password=<pwd>
subscription-manager list --available
subscription-manager attach --pool=<pool_id>
subscription-manager repos --enable=rhel-7-server-extras-rpms
----

Install docker and needed dependencies:
[source, bash]
----
yum install docker
----

Start the docker service:
[source, bash]
----
systemctl start docker.service
----

Enable the docker service:
[source, bash]
----
systemctl enable docker.service
----

== Installing PostgreSQL Server 9.5
Unless you already have a running PostgreSQL 9.5 Server installed, you will need
to install it.

To install PostgreSQL on a RHEL machine, make sure to enable the software collection 2.2
repository to get the required version of PostgreSQL.

----
subscription-manager repos --enable rhel-server-rhscl-7-rpms
----

Then install the server with:
----
yum install rh-postgresql95
scl enable rh-postgresql95 bash
postgresql-setup --initdb
service rh-postgresql95-postgresql start
----
