= Uninstalling the Middleware Manager

Uninstalling the Middleware Manager consists of several steps:

. Remove the Middleware provider from CloudForms
. Remove all agents from monitored EAPs
. Delete the Middleware provider container
. Delete the Cassandra container(s)
. Delete the metrics data
. Delete the inventory data

== Remove the Middleware provider from CloudForms

Navigate to the Middleware Provider then select `Configuration>Remove Middleware Provider`

== Remove all agents from monitored EAPs

For each EAP server (assuming installed in /opt/jboss-eap-7.0):

. Run the server in --admin-only mode:
+
----
/opt/jboss-eap-7.0/bin/standalone.sh --admin-only
----
. Remove the agent subsystem, the agent extension, and the socket binding that points to the Hawkular Server:
+
----
/opt/jboss-eap-7.0/jboss-cli.sh --connect --commands=/subsystem=hawkular-wildfly-agent/:remove,/extension=org.hawkular.agent/:remove,/socket-binding-group=standard-sockets/remote-destination-outbound-socket-binding=hawkular/:remove
----
. Remove the agent binaries:
+
----
rm -rf /opt/jboss-eap-7.0/modules/system/add-ons/hawkular-agent
----

== Delete the Middleware provider container

Make sure how the middleware provider container is named with `docker ps` command then execute:
----
docker rm -f mwmanager
----

== Delete the Cassandra containers
Make sure how the cassandra container is named with `docker ps` command then execute:
----
docker rm -f mwmanager-cassandra
----
You will need to execute the command for all the Cassandra nodes that you may have started.

== Delete the metrics data

WARNING: This operation is irreversible, all the metrics will be permanently deleted.

If you used the defaults setting, all the data should be stored in `/opt/apache-cassandra/data`.
Once all the containers are stopped and deleted, the folder can also be deleted:
----
rm -rf /opt/apache-cassandra/data
----

== Delete the inventory data

To properly delete the inventory data, you'll need to delete the database and the user that you may have created for this purpose.

First you will need to connect to the PostgreSQL database
----
su postgres
systemctl enable rh-postgresql95-postgresql.service
psql
----

Then execute the following commands
----
postgres=# DROP DATABASE mwmanager 
postgres=# DROP USER my_db_username
----
